version: '3'

services:

  app:
    image: devhab
    container_name: devhab
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/home/app
    ports:
      - 8080:8080
    environment:
      MONGO_HOST: mongodb
    networks:
      master_network:
        aliases:
          - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    networks:
      master_network:
        aliases:
          - app
networks:
  master_network:

